#!/bin/sh
#
# An example hook script to make use of push options.
# The example simply echoes all push options that start with 'echoback='
# and rejects all pushes when the "reject" push option is used.
#
# To enable this hook, rename this file to "pre-receive".

if [[ -x flake8 ]]; then
	flake8 || {
		echo "flake8 did not succeed. Aborting push. Please run flake8 and fix the warnings."
		exit 1
	}

	make mypy || {
		echo "mypy did not succeed. Aborting push. Please run `make mypy` and fix the warnings."
		exit 1
	}
fi