#!/bin/sh

python -m flake8 || {
	echo "flake8 did not succeed. Aborting push. Please run flake8 and fix the warnings."
	exit 1
}

make mypy || {
	echo "mypy did not succeed. Aborting push. Please run `make mypy` and fix the warnings."
	exit 1
}