repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
        types: [python]
  - repo: local
    hooks:
      - id: check-licenses
        name: Check Licenses
        description: Checks that all files have correct copyright licenses
        entry: pixi run -e dev check-licenses
        language: system
        types: [python]
        files: ^mantidimaging/

      - id: check-release-notes-format
        name: Check Release Notes Format
        description: Validate release note filename and contents format before commit
        entry: pixi run -e dev check-release-notes-format
        language: system
        files: ^docs/release_notes/next/

      - id: yapf
        name: yapf
        description: Checks that all files pass yapf checks
        entry: pixi run -e dev yapf
        language: system
        types: [python]
        files: ^mantidimaging/
        pass_filenames: false

      - id: mypy
        name: mypy
        description: Checks that all files pass mypy checks
        entry: pixi run -e dev mypy
        language: system
        types: [python]
        files: ^mantidimaging/
        pass_filenames: false

      - id: pyright
        name: pyright
        description: Checks that all files pass pyright checks
        entry: pixi run -e dev pyright
        language: system
        types: [python]
        files: ^mantidimaging/
        pass_filenames: false

      - id: ruff
        name: ruff
        description: Checks that all files pass ruff checks
        entry: pixi run -e dev ruff
        language: system
        types: [python]
        files: ^mantidimaging/
        pass_filenames: false
