on:
  push:
    paths:
      - CITATION.cff
    workflow_dispatch:

name: CITATION.cff
jobs:
  Validate-CITATION-cff:
    runs-on: ubuntu-latest
    name: Validate CITATION.cff
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install cffconvert
        run: |
          python3 -m pip install --user cffconvert
      - name: Validate CITATION.cff
        run: |
          cffconvert --validate --infile CITATION.cff
