name: Testing with CentOS 7 docker

on:
  push:
    branches:
    - 'main'
    - 'release-*'
  pull_request:
    branches:
      - 'main'
      - 'release-*'

jobs:
  test:
    # It is hosted on Ubuntu but the docker image is built on CentOS 7
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pre-load docker image
      run: docker pull mantidproject/mantidimaging:centos7

    - name: List versions
      uses: ./.github/actions/test
      with:
        command: python --version; conda list ; pip list
        label: centos7

    - name: yapf
      uses: ./.github/actions/test
      with:
        command: yapf --parallel --diff --recursive .
        label: centos7

    - name: flake8
      uses: ./.github/actions/test
      with:
        command: flake8
        label: centos7

    - name: mypy
      uses: ./.github/actions/test
      with:
        # COMPAT: applitools has some bad signatures, so use --no-site-packages
        command: mypy --ignore-missing-imports --no-site-packages mantidimaging
        label: centos7

    - name: pytest
      timeout-minutes: 5
      uses: ./.github/actions/test
      with:
        command: xvfb-run pytest -n auto --ignore=mantidimaging/eyes_tests --durations=10
        label: centos7
