name: Testing with Ubuntu 18 docker

on:
  push:
    branches:
    - 'main'
    - 'release-*'
  pull_request:
    branches:
      - 'main'
      - 'release-*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pre-load docker image
      run: docker pull mantidproject/mantidimaging:latest

    - name: List versions
      uses: ./.github/actions/test
      with:
        command: python --version; conda list ; pip list

    - name: yapf
      uses: ./.github/actions/test
      with:
        command: yapf --parallel --diff --recursive .

    - name: flake8
      uses: ./.github/actions/test
      with:
        command: flake8

    - name: mypy
      uses: ./.github/actions/test
      with:
        # COMPAT: applitools has some bad signatures, so use --no-site-packages
        command: mypy --ignore-missing-imports --no-site-packages mantidimaging

    - name: pytest
      timeout-minutes: 5
      uses: ./.github/actions/test
      with:
        command: xvfb-run pytest -n auto --ignore=mantidimaging/eyes_tests --durations=10
