name: Publish Mantid Imaging docs

inputs:
  token:
    description: 'Github API Token'
    required: true

runs:
  using: "composite"

  steps:
  - name: Publish docs
    shell: bash -l {0}
    run: |
      git config --global user.name mantid-builder
      git config --global user.email mantid-builder@hosting.com
      git config --global credential.helper store
      echo https://mantid-builder:${{ inputs.token }}@github.com > ~/.git-credentials
      python -m pip install gitpython
      python setup.py docs_publish
