{% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
{% set version_number = '.post' + version_number if version_number != '0' else '' %}
{% set version = version_tag + version_number %}

package:
  name: 'mantidimaging'
  version: '{{ version }}'

source:
  git_url: ../

requirements:
  build:
    - python=3.12.*
    - setuptools=62.*
  run:
    - python=3.12.*
    - pip
    - astropy=6.0.*
    - scipy=1.14.*
    - scikit-image=0.22.*
    - tifffile=2023.7.18
    - imagecodecs=2023.9.18
    - numpy=1.26.*
    - numexpr=2.8.*
    - algotom=1.6.*
    - tomopy=1.12.*
    - cudatoolkit=11.8.*
    - cupy=12.3.*
    - astra-toolbox=2.0.0
    - requests=2.27.*
    - h5py=3.9.*
    - hdf5=1.14.2
    - psutil=5.9.*
    - cil=24.0.*
    - ccpi-regulariser
    - jenkspy=0.4.*
    - pyqt=5.15.*
    - pyqtgraph=0.13.7
    - qt-material=2.14
    - darkdetect=0.8.0
    - qt-gtk-platformtheme # [linux]


build:
  number: 1
  entry_points:
    - mantidimaging = mantidimaging.main:main
    - mantidimaging-ipython = mantidimaging.ipython:main

test:
  imports:
    - mantidimaging

app:
  summary: "Mantid Imaging"
  own_environment: True

about:
  home: https://github.com/mantidproject/mantidimaging
  license: GPL-3
  license_file: LICENSE.txt
