name: Build conda package

inputs:
  repository:
    description: 'Anaconda repository'
    required: true
    default: 'mantid'
  label:
    description: 'Label'
    required: false
    default: 'unstable'
  token:
    description: 'Anaconda API Token'
    required: true

description: Build conda package
runs:
  using: "composite"

  steps:
  - name: Make build-env
    shell: bash -l {0}
    run: |
      conda config --set always_yes yes --set changeps1 no
      conda create -n build-env
      conda activate build-env
      conda install --yes conda-build anaconda-client conda-verify
      channels=$(cat environment-dev.yml | sed -ne '/channels:/,/dependencies:/{//!p}' | sed 's/ - / --append channels /g' | tr -d '\n') ; conda config --env $channels


#  - name: Build package
#    shell: bash -l {0}
#    run: |
#      conda activate build-env
#      conda config --set anaconda_upload yes
#      # if the upload silently fails - check the token expiration. Conda can fail silently!
#      conda build --user ${{ inputs.repository }} --token ${{ inputs.token }} --label ${{ inputs.label }} $GITHUB_WORKSPACE/conda |& tee upload.log
#      # Check that upload completed
#      grep "Upload complete" upload.log
