# This is a basic workflow to help you get started with Actions

name: Build conda package

inputs:
  repository:
    description: 'Anaconda repository'
    required: true
    default: 'mantid'
  label:
    description: 'Label'
    required: false
    default: 'unstable'
  token:
    description: 'Anaconda API Token'
    required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
description: Build conda package
runs:
  using: "composite"

  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
  - name: Make build-env
    shell: bash -l {0}
    run: |
      conda config --set always_yes yes --set changeps1 no
      conda create -n build-env anaconda python=3.7
      conda activate build-env
      conda install conda-build conda-verify

  - name: Build package
    shell: bash -l {0}
    run: |
      conda activate build-env
      conda config --set anaconda_upload yes
      # if the upload silently fails - check the token expiration. Conda can fail silently!
      conda build --user ${{ inputs.repository }} --token ${{ inputs.token }} --label ${{ inputs.label }} $GITHUB_WORKSPACE/conda
