name: Build conda package

inputs:
  repository:
    description: "Anaconda repository"
    required: true
    default: "mantidimaging"
  label:
    description: "Label"
    required: false
    default: "unstable"
  token:
    description: "Anaconda API Token"
    required: true

description: Build conda package
runs:
  using: "composite"

  steps:
    - name: Make build-env
      shell: bash -l {0}
      run: |
        conda create -n build-env --yes rattler-build anaconda-client
        conda activate build-env

    - name: Build package
      shell: bash -l {0}
      run: |
        conda activate build-env

        rattler-build build \
          -r $GITHUB_WORKSPACE/conda/recipe.yaml \
          --experimental \
          --output-dir $GITHUB_WORKSPACE/output/${{ inputs.label }} \
          --channel conda-forge \
          --channel astra-toolbox \
          --channel ccpi \
          --channel algotom \
          --channel https://software.repos.intel.com/python/conda/

    - name: Upload package
      shell: bash -l {0}
      run: |
        anaconda -t ${{ inputs.token }} upload \
        --user ${{ inputs.repository }} \
        --label ${{ inputs.label }} \
        $GITHUB_WORKSPACE/output/${{ inputs.label }}/**/mantidimaging*.conda \
        |& tee upload.log
        # Check that upload completed
        grep "Upload complete" upload.log
