name: Build conda package

inputs:
  repository:
    description: "Anaconda repository"
    required: true
    default: "mantidimaging"
  label:
    description: "Label"
    required: false
    default: "unstable"
  token:
    description: "Anaconda API Token"
    required: true

  debug_build:
    description: "List build output contents after build (for debugging)"
    default: "false"

description: Build conda package
runs:
  using: "composite"

  steps:
    - name: Build package
      shell: bash -l {0}
      run: |
        pixi run -e build-cpu rattler-build build --recipe $GITHUB_WORKSPACE/conda --experimental --config-file $GITHUB_WORKSPACE/conda/recipe_config.toml
        if [[ "${{ inputs.debug_build }}" == "true" ]]; then ls -R output; fi
        pixi run -e build-cpu anaconda -t ${{ inputs.token }} upload --force --user ${{ inputs.repository }} --label ${{ inputs.label }} output/**/*.conda |& tee upload.log
        # Check that upload completed
        grep "Upload complete" upload.log
