import * as names from 'names.js';

function main() {
    startApplication("python3.7 -m mantidimaging");
    activateItem(waitForObjectItem(names.mainWindowMenubarQMenuBar, "File"));
    activateItem(waitForObjectItem(names.mainWindowMenuFileQMenu, "Load"));
    clickButton(waitForObject(names.treeSelectQPushButton));
    clickButton(waitForObject(names.qFileDialogToParentButtonQToolButton));
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 190, 195, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 190, 195, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 190, 195, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 190, 195, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 190, 195, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 190, 195, -120, 0, 2);
    doubleClick(waitForObjectItem(names.stackedWidgetTreeViewQTreeView, "Tilt 1 \\_pre reco"), 111, 7, Qt.NoModifier, Qt.LeftButton);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 113, 144, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 113, 144, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 113, 144, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 113, 144, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 113, 144, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 113, 144, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 113, 144, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 113, 144, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 113, 144, -120, 0, 2);
    sendEvent("QWheelEvent", waitForObject(names.stackedWidgetTreeViewQTreeView), 113, 144, -120, 0, 2);
    doubleClick(waitForObjectItem(names.stackedWidgetTreeViewQTreeView, "Tomo\\_0000\\.tif"), 111, 5, Qt.NoModifier, Qt.LeftButton);
    clickButton(waitForObject(names.dialogOKQPushButton));
    waitForObject(names.mainWindowTomo0000QDockWidget);
    activateItem(waitForObjectItem(names.mainWindowMenubarQMenuBar, "Workflow"));
    activateItem(waitForObjectItem(names.mainWindowMenuWorkflowQMenu, "Operations"));
    mouseClick(waitForObject(names.splitterFilterSelectorQComboBox), 45, 7, Qt.NoModifier, Qt.LeftButton);
    mouseClick(waitForObjectItem(names.splitterFilterSelectorQComboBox, "Remove Outliers"), 42, 12, Qt.NoModifier, Qt.LeftButton);
    mouseDrag(waitForObject(names.filterPropertiesContainerQtSpinboxLineeditQLineEdit), 2, 13, 144, 5, 1, Qt.LeftButton);
    type(waitForObject(names.filterPropertiesContainerDifferenceQDoubleSpinBox), "<Backspace>");
    type(waitForObject(names.filterPropertiesContainerDifferenceQDoubleSpinBox), "2");
    type(waitForObject(names.filterPropertiesContainerDifferenceQDoubleSpinBox), "5");
    type(waitForObject(names.filterPropertiesContainerDifferenceQDoubleSpinBox), "0");
    clickButton(waitForObject(names.splitterSafeApplyQCheckBox));
    clickButton(waitForObject(names.splitterApplyToAllButtonQPushButton));
    clickButton(waitForObject(names.confirmActionOKQPushButton));
    waitForObject(names.splitterNotificationTextQTextEdit);
    mouseClick(waitForObject(names.splitterLayoutWidgetQWidget, 57585), 233, 7, Qt.NoModifier, Qt.LeftButton);
    mouseClick(waitForObject(names.splitterFilterSelectorQComboBox), 166, 8, Qt.NoModifier, Qt.LeftButton);
    mouseClick(waitForObjectItem(names.splitterFilterSelectorQComboBox, "ROI Normalisation"), 138, 5, Qt.NoModifier, Qt.LeftButton);
    clickButton(waitForObject(names.filterPropertiesContainerSelectROIQPushButton));
    sendEvent("QMoveEvent", waitForObject(names.selectROIQMainWindow), 171, 131, 185, 266);
    dragItemBy(waitForObject(names.qGraphicsRectItem), 149, 121, 75, 228, 1, Qt.LeftButton);
    clickButton(waitForObject(names.splitterOKQPushButton));
    clickButton(waitForObject(names.filterPropertiesContainerSelectROIQPushButton, 31666));
    sendEvent("QMoveEvent", waitForObject(names.selectROIQMainWindow), 171, 131, 204, 269);
    dragItemBy(waitForObject(names.qGraphicsRectItem), 151, 120, 130, 409, 1, Qt.LeftButton);
    clickButton(waitForObject(names.splitterOKQPushButton));
    clickButton(waitForObject(names.splitterApplyButtonQPushButton));
    mouseClick(waitForObject(names.splitterLayoutWidgetQWidget), 146, 8, Qt.NoModifier, Qt.LeftButton);
    mouseClick(waitForObject(names.splitterFilterSelectorQComboBox), 91, 0, Qt.NoModifier, Qt.LeftButton);
    mouseClick(waitForObjectItem(names.splitterFilterSelectorQComboBox, "Crop Coordinates"), 106, 21, Qt.NoModifier, Qt.LeftButton);
    clickButton(waitForObject(names.filterPropertiesContainerSelectROIQPushButton));
    sendEvent("QMoveEvent", waitForObject(names.selectROIQMainWindow), 171, 131, 170, 262);
    dragItemBy(waitForObject(names.qGraphicsRectItem), 149, 119, 105, 335, 1, Qt.LeftButton);
    dragItemBy(waitForObject(names.qGraphicsRectItem), 164, 363, 163, 40, 1, Qt.LeftButton);
    dragItemBy(waitForObject(names.qGraphicsRectItem), 421, 493, -37, -65, 1, Qt.LeftButton);
    dragItemBy(waitForObject(names.qGraphicsRectItem), 343, 407, 23, 22, 1, Qt.LeftButton);
    dragItemBy(waitForObject(names.qGraphicsRectItem), 405, 452, -30, -42, 1, Qt.LeftButton);
    dragItemBy(waitForObject(names.qGraphicsRectItem), 322, 352, 15, 16, 1, Qt.LeftButton);
    clickButton(waitForObject(names.splitterOKQPushButton));
    clickButton(waitForObject(names.splitterApplyToAllButtonQPushButton));
    clickButton(waitForObject(names.confirmActionOKQPushButton));
    sendEvent("QResizeEvent", waitForObject(names.dialogAsyncTaskDialogView), 761, 70, 983, 530);
    mouseClick(waitForObject(names.splitterFilterSelectorQComboBox, 150654), 65, 14, Qt.NoModifier, Qt.LeftButton);
    mouseClick(waitForObjectItem(names.splitterFilterSelectorQComboBox, "Flat-fielding"), 56, 7, Qt.NoModifier, Qt.LeftButton);
    clickButton(waitForObject(names.splitterApplyButtonQPushButton));
    sendEvent("QCloseEvent", waitForObject(names.filtersWindowFiltersWindowView));
    activateItem(waitForObjectItem(names.mainWindowMenubarQMenuBar, "Workflow"));
    activateItem(waitForObjectItem(names.mainWindowMenuWorkflowQMenu, "Reconstruct"));
    sendEvent("QMoveEvent", waitForObject(names.reconstructionWindowReconstructWindowView), 133, 93, 185, 135);
    clickButton(waitForObject(names.resultGroupCalculateCorsQPushButton));
    clickButton(waitForObject(names.groupBoxCorrelateBtnQPushButton));
    clickButton(waitForObject(names.groupBoxMinimiseBtnQPushButton));
    clickButton(waitForObject(names.numberOfSlicesOKQPushButton));
    clickTab(waitForObject(names.splitterTabWidgetQTabWidget), "Reconstruct");
    clickButton(waitForObject(names.reconTabReconstructVolumeQPushButton));
    sendEvent("QCloseEvent", waitForObject(names.reconstructionWindowReconstructWindowView, 72337));
    test.vp("VP1");
    mouseClick(waitForObject(names.qGraphicsRectItem_2), 202, 5, Qt.NoModifier, Qt.LeftButton);
    test.vp("VP2");
    mouseClick(waitForObject(names.qGraphicsRectItem_2), 359, 15, Qt.NoModifier, Qt.LeftButton);
    test.vp("VP3");
    mouseClick(waitForObject(names.roiPlotPlotItem), 613, 19, Qt.NoModifier, Qt.LeftButton);
    test.vp("VP4");
}
