# This is a basic workflow to help you get started with Actions

name: Testing with CentOS 7 docker

on:
  push:
    branches:
    - 'main'
    - 'release-*'
  pull_request:
    branches:
      - 'main'
      - 'release-*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    # It is hosted on Ubuntu but the docker image is built on CentOS 7
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check License Lines
      uses: kt3k/license_checker@v1.0.3

    - name: Pre-load docker image
      run: docker pull mantidproject/mantidimaging:centos7

    - name: List versions
      uses: ./.github/actions/test
      with:
        command: python --version; conda list ; pip list
        label: centos7

    - name: yapf
      uses: ./.github/actions/test
      with:
        command: yapf --parallel --diff --recursive .
        label: centos7

    - name: flake8
      uses: ./.github/actions/test
      with:
        command: flake8
        label: centos7

    - name: mypy
      uses: ./.github/actions/test
      with:
        # COMPAT: applitools has some bad signatures, so use --no-site-packages
        command: mypy --ignore-missing-imports --no-site-packages mantidimaging
        label: centos7

    - name: pytest
      timeout-minutes: 5
      uses: ./.github/actions/test
      with:
        command: xvfb-run pytest -n auto --ignore=mantidimaging/eyes_tests
        label: centos7

    - name: docs
      uses: ./.github/actions/test
      with:
        command: python setup.py docs
        label: centos7
