name: Testing with conda

on:
  push:
    branches:
      - "main"
      - "release-*"
  pull_request:
    paths:
      - "**"
      - "!docs/**"
  release:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-conda:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Needed to get tags so that git describe works during package build
          fetch-depth: "0"

      # Always label as unstable. Builds of stable releases can be manually labeled to 'main' once tested
      - name: publish 'unstable' package
        if: github.event_name == 'release' || (github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release')))
        uses: ./.github/actions/publish-package
        with:
          label: unstable
          token: ${{ secrets.ANACONDA_API_TOKEN_MANTIDIMAGING }}
        timeout-minutes: 120

      - name: Show disk space at end
        if: ${{ !cancelled() }}
        run: |
          df -h
        shell: bash
