name: Build docs

on:
  push:
    branches:
      - "main"
      - "release-*"
  pull_request:
  release:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: v0.59.0
          environments: >-
            dev
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: docs
        run: |
          pixi run -e dev build-docs
        env:
          QT_QPA_PLATFORM: offscreen

      - name: publish docs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ./.github/actions/publish-docs
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: publish docs release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/release')
        uses: ./.github/actions/publish-docs
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          dir_name: ${{ github.ref_name }}

      - name: Show disk space at end
        if: ${{ !cancelled() }}
        run: |
          df -h
        shell: bash
