name: Testing with Rocky docker

on:
  push:
    branches:
      - "main"
      - "release-*"
  pull_request:
    paths:
      - "**"
      - "!docs/**"
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-docker-rocky:
    # It is hosted on Ubuntu but the docker image is built on Rocky
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Pre-load docker image
        run: docker pull ghcr.io/mantidproject/mantidimaging:rocky8

      - name: yapf
        uses: ./.github/actions/test
        with:
          command: pixi run yapf
          label: rocky8

      - name: ruff
        uses: ./.github/actions/test
        with:
          command: pixi run ruff
          label: rocky8

      - name: mypy
        uses: ./.github/actions/test
        with:
          command: pixi run mypy
          label: rocky8

      - name: pytest
        timeout-minutes: 5
        uses: ./.github/actions/test
        with:
          command: pixi run -e dev xvfb-run pytest -n auto --maxprocesses=4 --dist loadgroup -o log_cli=true --ignore=mantidimaging/eyes_tests --durations=10
          label: rocky8
